name: Novacraft
author: The_Dude___
version: 1.0.0
main: io.novacraft.Novacraft
api-version: 1.14
description: Novacrafts plugin suite
commands:
  skin:
    description: Changes your skin to whatever you set.
  resetcooldown:
    description: Admin Command
  rtp:
    description: Random teleportation! :)
  a:
    description: Contact staff with this command.
  ma:
    description: Contact staff with this command.
  ra:
    description: Contact staff with this command.
  getmoonphase:
    description: Get's the current moon phase.
  trophy:
    description: Trophy Management command.