name: Novacraft
author: The_Dude___
version: 1.0.0
main: io.novacraft.Novacraft
api-version: 1.14
description: Novacrafts plugin suite
commands:
  skin:
    description: Changes your skin to whatever you set.
  rtp:
    description: Random teleportation! :)
  sc:
    permission: staffchat.use
    permission-message: "§cYou don't have permission to execute this command!"
    description: What's this?
  dungeons:
    description: join epic dungoeons for cool prizes :)
  opdungeons:
    description: command for configuring plugin